// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "cff6377ee226c48a88ca944e3da1c22354f178cae1b23b4458e5b8355c163271")
